void bulbasaur_pokemon(){
    printf("                                           /\n");
    printf("                        _,.------....___,.' ',.-.\n");
    printf("                     ,-'          _,.--\"        |\n");
    printf("                   ,'         _.-'              .\n");
    printf("                  /   ,     ,'                   `\n");
    printf("                 .   /     /                     ``.\n");
    printf("                 |  |     .                       \\.\\\n");
    printf("       ____      |___._.  |       __               \\ `.\n");
    printf("     .'    `---\"\"       ``\"-.--\"'`  \\               .  \\\n");
    printf("    .  ,            __               `              |   .\n");
    printf("    `,'         ,-\"'  .               \\             |    L\n");
    printf("   ,'          '    _.'                -._          /    |\n");
    printf("  ,`-.    ,\".   `--'                      >.      ,'     |\n");
    printf(" . .'\\'   `-'       __    ,  ,-.         /  `.__.-      ,'\n");
    printf(" ||:, .           ,'  ;  /  / \\ `        `.    .      .'/\n");
    printf(" j|:D  \\          `--'  ' ,'_  . .         `.__, \\   , /\n");
    printf("/ L:_  |                 .  \"' :_;                `.'.'\n");
    printf(".    \"\"'                  \"\"\"\"\"'                    V\n");
    printf(" `.                                 .    `.   _,..  `\n");
    printf("   `,_   .    .                _,-'/    .. `,'   __  `\n");
    printf("    ) \\`._        ___....----\"'  ,'   .'  \\ |   '  \\  .\n");
    printf("   /   `. \"`-.--\"'         _,' ,'     `---' |    `./  |\n");
    printf("  .   _  `\"\"'--.._____..--\"   ,             '         |\n");
    printf("  | .\" `. `-.                /-.           /          ,\n");
    printf("  | `._.'    `,_            ;  /         ,'          .\n");
    printf(" .'          /| `-.        . ,'         ,           ,\n");
    printf(" '-.__ __ _,','    '`-..___;-...__   ,.'\\ ____.___.'\n");
    printf(" `\"^--'..'   '-`-^-'\"--    `-^-'`.''\"\"\"\"\"`.,^.`.--' mh\n");
    }
    void oppbulbasaur_pokemon(){
    printf("\t\t\t\t\t\t\t\t\t\t\t                                           /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                        _,.------....___,.' ',.-.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                     ,-'          _,.--\"        |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   ,'         _.-'              .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                  /   ,     ,'                   `\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                 .   /     /                     ``.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                 |  |     .                       \\.\\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t       ____      |___._.  |       __               \\ `.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     .'    `---\"\"       ``\"-.--\"'`  \\               .  \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t    .  ,            __               `              |   .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t    `,'         ,-\"'  .               \\             |    L\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t   ,'          '    _.'                -._          /    |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  ,`-.    ,\".   `--'                      >.      ,'     |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t . .'\\'   `-'       __    ,  ,-.         /  `.__.-      ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t ||:, .           ,'  ;  /  / \\ `        `.    .      .'/\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t j|:D  \\          `--'  ' ,'_  . .         `.__, \\   , /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t/ L:_  |                 .  \"' :_;                `.'.'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t.    \"\"'                  \"\"\"\"\"'                    V\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t `.                                 .    `.   _,..  `\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t   `,_   .    .                _,-'/    .. `,'   __  `\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t    ) \\`._        ___....----\"'  ,'   .'  \\ |   '  \\  .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t   /   `. \"`-.--\"'         _,' ,'     `---' |    `./  |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  .   _  `\"\"'--.._____..--\"   ,             '         |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  | .\" `. `-.                /-.           /          ,\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  | `._.'    `,_            ;  /         ,'          .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t .'          /| `-.        . ,'         ,           ,\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t '-.__ __ _,','    '`-..___;-...__   ,.'\\ ____.___.'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t `\"^--'..'   '-`-^-'\"--    `-^-'`.''\"\"\"\"\"`.,^.`.--' mh\n");
    }
   void charchar_pokemon(){
    printf("              _.--\"\"`-..\n");
    printf("            ,'          `.\n");
    printf("          ,'          __  `.\n");
    printf("         /|          \" __   \\\n");
    printf("        , |           / |.   .\n");
    printf("        |,'          !_.'|   |\n");
    printf("      ,'             '   |   |\n");
    printf("     /              |`--'|   |\n");
    printf("    |                `---'   |\n");
    printf("     .   ,                   |                       ,\".\n");
    printf("      ._     '           _'  |                    , ' \\ `\n");
    printf("  `.. `.`-...___,...---\"\"    |       __,.        ,`\"   L,|\n");
    printf("  |, `- .`._        _,-,.'   .  __.-'-. /        .   ,    \\\n");
    printf("-:..     `. `-..--_.,.<       `\"      / `.        `-/ |   .\n");
    printf("  `,         \"\"\"\"'     `.              ,'         |   |  ',,\n");
    printf("    `.      '            '            /          '    |'. |/\n");
    printf("      `.   |              \\       _,-'           |       ''\n");
    printf("        `._'               \\   '\"\\                .      |\n");
    printf("           |                '     \\                `._  ,'\n");
    printf("           |                 '     \\                 .'|\n");
    printf("           |                 .      \\                | |\n");
    printf("           |                 |       L              ,' |\n");
    printf("           `                 |       |             /   '\n");
    printf("            \\                |       |           ,'   /\n");
    printf("          ,' \\               |  _.._ ,-..___,..-'    ,'\n");
    printf("         /     .             .      `!             ,j'\n");
    printf("        /       `.          /        .           .'/\n");
    printf("       .          `.       /         |        _.'.'\n");
    printf("        `.          7`'---'          |------\"'_.'\n");
    printf("       _,.`,_     _'                ,''-----\"'\n");
    printf("   _,-_    '       `.     .'      ,\\\n");
    printf("   -\" /`.         _,'     | _  _  _.|\n");
    printf("    \"\"--'---\"\"\"\"\"'        `' '! |! /\n");
    printf("                            `\" \" -' mh\n");
    printf("\n");
    printf("\n");
   }
   void oppcharchar_pokemon(){
    printf("\t\t\t\t\t\t\t\t\t\t\t              _.--\"\"`-..\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            ,'          `.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t          ,'          __  `.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t         /|          \" __   \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        , |           / |.   .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        |,'          !_.'|   |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      ,'             '   |   |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     /              |`--'|   |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t    |                `---'   |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     .   ,                   |                       ,\".\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      ._     '           _'  |                    , ' \\ `\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  `.. `.`-...___,...---\"\"    |       __,.        ,`\"   L,|\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  |, `- .`._        _,-,.'   .  __.-'-. /        .   ,    \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t-:..     `. `-..--_.,.<       `\"      / `.        `-/ |   .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  `,         \"\"\"\"'     `.              ,'         |   |  ',,\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t    `.      '            '            /          '    |'. |/\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      `.   |              \\       _,-'           |       ''\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        `._'               \\   '\"\\                .      |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           |                '     \\                `._  ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           |                 '     \\                 .'|\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           |                 .      \\                | |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           |                 |       L              ,' |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           `                 |       |             /   '\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            \\                |       |           ,'   /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t          ,' \\               |  _.._ ,-..___,..-'    ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t         /     .             .      `!             ,j'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        /       `.          /        .           .'/\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t       .          `.       /         |        _.'.'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        `.          7`'---'          |------\"'_.'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t       _,.`,_     _'                ,''-----\"'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t   _,-_    '       `.     .'      ,\\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t   -\" /`.         _,'     | _  _  _.|\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t    \"\"--'---\"\"\"\"\"'        `' '! |! /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                            `\" \" -' mh\n");
   }
   void Squirtle(){
    printf("               _,........__\n");
    printf("            ,-'            \"`-.\n");
    printf("          ,'                   `-.\n");
    printf("        ,'                        \\\n");
    printf("      ,'                           .\n");
    printf("      .'\\               ,\"\".       `\n");
    printf("     ._.'|             / |  `       \\\n");
    printf("     |   |            `-.'  ||       `.\n");
    printf("     |   |            '-._,'||       | \\\n");
    printf("     .`.,'             `..,'.'       , |`-.\n");
    printf("     l                       .'`.  _/  |   `.\n");
    printf("     `-.._'-   ,          _ _'   -\" \\  .     `\n");
    printf("`.\"\"\"\"\"'-.`-...,---------','         `. `....__.\n");
    printf(".'        `\"-..___      __,'\\          \\  \\     \\\n");
    printf("\\_ .          |   `\"\"\"\"'    `.           . \\     \\\n");
    printf("  `.          |              `.          |  .     L\n");
    printf("    `.        |`--...________.'.        j   |     |\n");
    printf("      `._    .'      |          `.     .|   ,     |\n");
    printf("         `--,\\       .            `7\"\"' |  ,      |\n");
    printf("            ` `      `            /     |  |      |    _,-'\"\"\"`-.\n");
    printf("             \\ `.     .          /      |  '      |  ,'          `.\n");
    printf("              \\  v.__  .        '       .   \\    /| /              \\\n");
    printf("               \\/    `\"\"\\\"\"\"\"\"\"\"`.       \\   \\  /.''                |\n");
    printf("                `        .        `._ ___,j.  `/ .-       ,---.     |\n");
    printf("                ,`-.      \\         .\"     `.  |/        j     `    |\n");
    printf("               /    `.     \\       /         \\ /         |     /    j\n");
    printf("              |       `-.   7-.._ .          |\"          '         /\n");
    printf("              |          `./_    `|          |            .     _,'\n");
    printf("              `.           / `----|          |-............`---'\n");
    printf("                \\          \\      |          |\n");
    printf("               ,'           )     `.         |\n");
    printf("                7____,,..--'      /          |\n");
    printf("                                  `---.__,--.'mh\n");
    }
    void oppSquirtle(){
    printf("\t\t\t\t\t\t\t\t\t\t\t               _,........__\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            ,-'            \"`-.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t          ,'                   `-.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        ,'                        \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      ,'                           .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      .'\\               ,\"\".       `\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     ._.'|             / |  `       \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     |   |            `-.'  ||       `.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     |   |            '-._,'||       | \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     .`.,'             `..,'.'       , |`-.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     l                       .'`.  _/  |   `.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     `-.._'-   ,          _ _'   -\" \\  .     `\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t`.\"\"\"\"\"'-.`-...,---------','         `. `....__.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t.'        `\"-..___      __,'\\          \\  \\     \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t\\_ .          |   `\"\"\"\"'    `.           . \\     \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  `.          |              `.          |  .     L\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t    `.        |`--...________.'.        j   |     |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      `._    .'      |          `.     .|   ,     |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t         `--,\\       .            `7\"\"' |  ,      |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            ` `      `            /     |  |      |    _,-'\"\"\"`-.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t             \\ `.     .          /      |  '      |  ,'          `.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t              \\  v.__  .        '       .   \\    /| /              \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t               \\/    `\"\"\\\"\"\"\"\"\"\"`.       \\   \\  /.''                |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                `        .        `._ ___,j.  `/ .-       ,---.     |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                ,`-.      \\         .\"     `.  |/        j     `    |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t               /    `.     \\       /         \\ /         |     /    j\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t              |       `-.   7-.._ .          |\"          '         /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t              |          `./_    `|          |            .     _,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t              `.           / `----|          |-............`---'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                \\          \\      |          |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t               ,'           )     `.         |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                7____,,..--'      /          |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                                  `---.__,--.'mh\n");
    }
    void beautifly_pokemon(){
    printf("       ,-.                                            ___.._\n");
    printf(" _     `. `.                                    _,-\"\"\"      ',._\n");
    printf("`.`.      `.\\                                _,'         _..-'  `.\n");
    printf("  `._\\       `.                            ,'         _,'_,.-'-.  \\\n");
    printf("      `.       `.                        ,'        ,-',-\"       \\  .\n");
    printf("        `.       \\                      /  _,----\"',-'           L  L\n");
    printf("          `.      \\                   ,' _.--\"-.  [              |  |\n");
    printf("            `.     .                 / ,'       | |     _..---../   |\n");
    printf("              .     L               / /         | j ,.-'        `   |\n");
    printf("               \\    .              ' /          j ,'             |  |\n");
    printf("                \\    .            ' /          ' /               |  |\n");
    printf("                 \\   l           / /          /,'                j  '\n");
    printf("                  L__L._        / /          +'      __,........'  j\n");
    printf("                ,'   '  \"`.    / /         .' _,.--'\"           \\  |\n");
    printf("               /,\"\"-.      `. ' '        _/.-'                  | F\n");
    printf("              /|   / l       . /       ,'                       | |\n");
    printf("             | |  /  |       ]'      ,'                         | |\n");
    printf("            ,._\\\"'   |       |     ,'-'\"\"\"\"\"\"\"\"\"\"\"\"\"'----.._    / |\n");
    printf("            |  \\`.._,'       F  _,'                         `--'  |\n");
    printf("            `..'           _/ ,:_____                         L   |\n");
    printf("              `..          .-'       `'--.._                   | j\n");
    printf("            _,. /,---.       \\              `--..              | |\n");
    printf("           F  <j-.'   `       ._                 `\"-._        j  '\n");
    printf("           |  <|`,.    |       `L._                   `..   _, ,'\n");
    printf("           `..<|`.___,'        |.  `-.                   Y\"' _.\n");
    printf("              `L               | `.   `-.._____________,',.-'\n");
    printf("                `.            .Y   \\      `\"\".\"\"\"\"\".  .\"'\n");
    printf("                  `.        ,' |\\   `.        `+-._ \\  |\n");
    printf("                    `,--. -'   | .    `.       `   `.| |\n");
    printf("                    /    //    |  \\    ``-..___/     | |\n");
    printf("                   j    .l     |   .    F   \\   `   F  |\n");
    printf("                   |    ||     |    `   `    .   ` ,  /\n");
    printf("                   |    ||    F      `-.|     . _,' _'\n");
    printf("                   |   / |    |       `._`-----'  ,'\n");
    printf("                   |  /  |   /           `-------'\n");
    printf("                   l /   \\_,'\n");
    printf("                    \" mh\n");
    }
    void oppbeautifly_pokemon(){
    printf("\t\t\t\t\t\t\t\t\t\t\t       ,-.                                            ___.._\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t _     `. `.                                    _,-\"\"\"      ',._\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t`.`.      `.\\                                _,'         _..-'  `.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  `._\\       `.                            ,'         _,'_,.-'-.  \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      `.       `.                        ,'        ,-',-\"       \\  .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        `.       \\                      /  _,----\"',-'           L  L\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t          `.      \\                   ,' _.--\"-.  [              |  |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            `.     .                 / ,'       | |     _..---../   |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t              .     L               / /         | j ,.-'        `   |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t               \\    .              ' /          j ,'             |  |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                \\    .            ' /          ' /               |  |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                 \\   l           / /          /,'                j  '\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                  L__L._        / /          +'      __,........'  j\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                ,'   '  \"`.    / /         .' _,.--'\"           \\  |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t               /,\"\"-.      `. ' '        _/.-'                  | F\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t              /|   / l       . /       ,'                       | |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t             | |  /  |       ]'      ,'                         | |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            ,._\\\"'   |       |     ,'-'\"\"\"\"\"\"\"\"\"\"\"\"\"'----.._    / |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            |  \\`.._,'       F  _,'                         `--'  |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            `..'           _/ ,:_____                         L   |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t              `..          .-'       `'--.._                   | j\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            _,. /,---.       \\              `--..              | |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           F  <j-.'   `       ._                 `\"-._        j  '\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           |  <|`,.    |       `L._                   `..   _, ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           `..<|`.___,'        |.  `-.                   Y\"' _.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t              `L               | `.   `-.._____________,',.-'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                `.            .Y   \\      `\"\".\"\"\"\"\".  .\"'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                  `.        ,' |\\   `.        `+-._ \\  |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                    `,--. -'   | .    `.       `   `.| |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                    /    //    |  \\    ``-..___/     | |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   j    .l     |   .    F   \\   `   F  |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   |    ||     |    `   `    .   ` ,  /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   |    ||    F      `-.|     . _,' _'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   |   / |    |       `._`-----'  ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   |  /  |   /           `-------'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   l /   \\_,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                    \" mh\n");
    }
    void talonflame_pokemon(){
    printf("               _,\n");
    printf("             .'.'  _.\n");
    printf("           ,' ._,-'_\"'\n");
    printf("        _,'   '  ------\"\"'`._\n");
    printf("      ,'                 _,.--\"'              ___        __,..\n");
    printf("      |    _,..       ,-'             _,.--\"\"'   7_,.--\"'    ,'\n");
    printf("      j. .'D  |       |            ,'\"       _.-'       _.-\"\"'.  _,..-\"'\n");
    printf(" ,---'  `+----'       |`._      _.'         '                '.-'      /\n");
    printf("j         `.       ,-'    `'--,\"                           ,'       ,-'\n");
    printf("|    __    |      '-.._,    .'                           ,'     ,.-'\n");
    printf("`. ,' ('T--'        .\"     /                          _.'  _,--\"\n");
    printf("  `   `,  /         _`.   j                         _', ,-\"__,..,-.\n");
    printf("      `-\"`.        \\   `-.|                        _,'\"\"\"\"'       l\n");
    printf("           `.,      \\     L                     _.'      __,...--'\n");
    printf("            ` '-    .`     `._             _,.-' ,--'\"\"\"\"\n");
    printf("             '  \\`.,\\         `+------,--\"'     /\n");
    printf("                 \\ )`'      ,-'      /         /\n");
    printf("                  `     _,-'       ,'         /\n");
    printf("                   `+\"\"'         ,'     ,.  ,'\n");
    printf("                     `.        ,'     ,'   .\n");
    printf("                       `-._.,-'      /. _.,j\n");
    printf("                           \"\"`-----.'  '  /\n");
    printf("                                / /   /  /\n");
    printf("                    _.......__,' /__,' ,'\n");
    printf("                  ,\\  ,--..--------\"_  ...._\n");
    printf("                 '--\"(_,`|  ,..-' _,....__  |.\n");
    printf("                        '-./...-'\"        `\"\"\"- mh\n");
    }
    void opptalonflame_pokemon(){
    printf("\t\t\t\t\t\t\t\t\t\t\t               _,\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t             .'.'  _.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           ,' ._,-'_\"'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        _,'   '  ------\"\"'`._\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      ,'                 _,.--\"'              ___        __,..\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      |    _,..       ,-'             _,.--\"\"'   7_,.--\"'    ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      j. .'D  |       |            ,'\"       _.-'       _.-\"\"'.  _,..-\"'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t ,---'  `+----'       |`._      _.'         '                '.-'      /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\tj         `.       ,-'    `'--,\"                           ,'       ,-'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t|    __    |      '-.._,    .'                           ,'     ,.-'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t`. ,' ('T--'        .\"     /                          _.'  _,--\"\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  `   `,  /         _`.   j                         _', ,-\"__,..,-.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      `-\"`.        \\   `-.|                        _,'\"\"\"\"'       l\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           `.,      \\     L                     _.'      __,...--'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            ` '-    .`     `._             _,.-' ,--'\"\"\"\"\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t             '  \\`.,\\         `+------,--\"'     /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                 \\ )`'      ,-'      /         /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                  `     _,-'       ,'         /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   `+\"\"'         ,'     ,.  ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                     `.        ,'     ,'   .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                       `-._.,-'      /. _.,j\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                           \"\"`-----.'  '  /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                                / /   /  /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                    _.......__,' /__,' ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                  ,\\  ,--..--------\"_  ...._\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                 '--\"(_,`|  ,..-' _,....__  |.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                        '-./...-'\"        `\"\"\"- mh\n");
    }
   void ekans_pokemon(){
    printf("        _,--\"\"'\"\"\"-.\n");
    printf("      ,'   .,-.     `.\n");
    printf("     '`...( |  |      \\\n");
    printf("    |      `--'        .\n");
    printf("    '_,...__,'          `\n");
    printf("     `._                 `\n");
    printf("        `..______         |\n");
    printf("             |.          ,|\n");
    printf("             | `-.....,-\" |\n");
    printf("             |            j\n");
    printf("             ^.         _F\n");
    printf("            /  `-.....-'/\n");
    printf("           /          ,'\n");
    printf("          /          /\n");
    printf("         /          /\n");
    printf("        j       _.-- .\n");
    printf("        |      /     ,+---....___\n");
    printf("        L     /     /            \"\"`-.._\n");
    printf("         \\   j     j                    `-.\n");
    printf("          `. |     |            .'         `\n");
    printf("            `+...__|__       .,+-..         |\n");
    printf("                      \"\"`._.l      `.       j\n");
    printf("                      ,.-\"   \"-.     L    ,'\n");
    printf("                    ,'          L    : _.'\n");
    printf("                   /            |   _:'\n");
    printf("                  .            .|,-'\n");
    printf("                   .            `.._\n");
    printf("   '\\               `-.             `\"-.\n");
    printf(" ,`.'                  `-.              L\n");
    printf(" |  )                     `-. _...__     |\n");
    printf(".'-'                         )      `.   j\n");
    printf("|  |_                      _,'\"\"`.    \\ /\n");
    printf(" .-' `+._               _,\"       `.  |/\n");
    printf("  \\   |  \"`,,,,,....---'           | .'\n");
    printf("   `-.'   /                        |+\n");
    printf("      `--+                     _.-'\n");
    printf("          `--.___       __.---'\n");
    printf("                 `\"\"\"\"\"\" mh\n");
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
   }
void oppekans_pokemon(){
    printf("\t\t\t\t\t\t\t\t\t\t\t        _,--\"\"'\"\"\"-.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      ,'   .,-.     `.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     '`...( |  |      \\\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t    |      `--'        .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t    '_,...__,'          `\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t     `._                 `\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        `..______         |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t             |.          ,|\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t             | `-.....,-\" |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t             |            j\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t             ^.         _F\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            /  `-.....-'/\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t           /          ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t          /          /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t         /          /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        j       _.-- .\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        |      /     ,+---....___\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t        L     /     /            \"\"`-.._\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t         \\   j     j                    `-.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t          `. |     |            .'         `\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t            `+...__|__       .,+-..         |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                      \"\"`._.l      `.       j\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                      ,.-\"   \"-.     L    ,'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                    ,'          L    : _.'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   /            |   _:'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                  .            .|,-'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                   .            `.._\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t   '\\               `-.             `\"-.\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t ,`.'                  `-.              L\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t |  )                     `-. _...__     |\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t.'-'                         )      `.   j\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t|  |_                      _,'\"\"`.    \\ /\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t .-' `+._               _,\"       `.  |/\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t  \\   |  \"`,,,,,....---'           | .'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t   `-.'   /                        |+\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t      `--+                     _.-'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t          `--.___       __.---'\n");
    printf("\t\t\t\t\t\t\t\t\t\t\t                 `\"\"\"\"\"\" mh\n");
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
   }
  void pikachu(){
  printf("                                             ,-.\n");
    printf("                                          _.|  '\n");
    printf("                                        .'  | /\n");
    printf("                                      ,'    |'\n");
    printf("                                     /      /\n");
    printf("                       _..----\"\"---.'      /\n");
    printf(" _.....---------...,-\"\"                  ,'\n");
    printf(" `-._  \\                                /\n");
    printf("     `-.+_            __           ,--. .\n");
    printf("          `-.._     .:  ).        (`--\"| \\\n");
    printf("               7    | `\" |         `...'  \\\n");
    printf("               |     `--'     '+\"        ,\". ,\"\"-\n");
    printf("               |   _...        .____     | |/    '\n");
    printf("          _.   |  .    `.  '--\"   /      `./     j\n");
    printf("         \\' `-.|  '     |   `.   /        /     /\n");
    printf("         '     `-. `---\"      `-\"        /     /\n");
    printf("          \\       `.                  _,'     /\n");
    printf("           \\        `                        .\n");
    printf("            \\                                j\n");
    printf("             \\                              /\n");
    printf("              `.                           .\n");
    printf("                +                          \\\n");
    printf("                |                           L\n");
    printf("                |                           |\n");
    printf("                |  _ /,                     |\n");
    printf("                | | L)'..                   |\n");
    printf("                | .    | `                  |\n");
    printf("                '  \\'   L                   '\n");
    printf("                 \\  \\   |                  j\n");
    printf("                  `. `__'                 /\n");
    printf("                _,.--.---........__      /\n");
    printf("               ---.,'---`         |   -j\"\n");
    printf("                .-'  '....__      L    |\n");
    printf("              \"\"--..    _,-'       \\ l||\n");
    printf("                  ,-'  .....------. `||'\n");
    printf("               _,'                /\n");
    printf("             ,'                  /\n");
    printf("            '---------+-        /\n");
    printf("                     /         /\n");
    printf("                   .'         /\n");
    printf("                 .'          /\n");
    printf("               ,'           /\n");
    printf("             _'....----\"\"\"\"\" mh\n");
  }
